<?php require_once __DIR__ . '/../../partials/helpers.php'; ob_start();
$activeNav = 'helpdesk-admin';
$areaLabel = 'Help Desk';
$scripts = ['/js/helpdesk.js'];
$isNew = $row === null;
$action = $isNew ? '/helpdesk/admin/' . $kind : '/helpdesk/admin/' . $kind . '/' . (int) $row['id'];
$back = '/helpdesk/admin?tab=' . $kind;
$val = static fn (string $key, string $default = ''): string => form_value($row, $key, $default);
$businessDays = array_filter(explode(',', $val('business_days', '1,2,3,4,5')));
$checkedIn = static fn (array $values, mixed $value): string => in_array((string) $value, array_map('strval', $values), true) ? ' checked' : '';
$optionRows = static function (array $items, string $current, string $empty = '– keine –'): void { ?><option value=""><?= e($empty) ?></option><?php foreach ($items as $item): ?><option value="<?= (int) $item['id'] ?>"<?= selected($current, $item['id']) ?>><?= e(($item['parent_name'] ?? null) ? $item['parent_name'] . ' / ' . $item['name'] : ($item['display_name'] ?? $item['name'] ?? $item['username'] ?? '–')) ?></option><?php endforeach; ?><?php };
?>
<div class="page-header"><div><h1 class="page-title"><?= e($title) ?></h1><p class="page-subtitle text-muted"><?= e($kinds[$kind] ?? $kind) ?></p></div><div class="page-actions"><a class="btn btn-ghost" href="<?= e($back) ?>"><?= icon('arrow-left') ?> Zurück</a></div></div>
<div class="card card-form card-form-wide">
    <form method="post" action="<?= e($action) ?>" novalidate>
        <?= csrf_field() ?>
        <?php if (in_array($kind, ['types', 'statuses', 'priorities'], true)): ?>
            <div class="form-row">
                <div class="form-group<?= has_error('code') ? ' has-error' : '' ?>"><label for="f-code">Code <span class="required">*</span></label><input id="f-code" name="code" value="<?= e($val('code')) ?>" maxlength="30" class="mono" required><?= field_error('code') ?></div>
                <div class="form-group<?= has_error('name') ? ' has-error' : '' ?>"><label for="f-name">Bezeichnung <span class="required">*</span></label><input id="f-name" name="name" value="<?= e($val('name')) ?>" maxlength="100" required autofocus><?= field_error('name') ?></div>
            </div>
            <div class="form-group<?= has_error('description') ? ' has-error' : '' ?>"><label for="f-description">Beschreibung</label><input id="f-description" name="description" value="<?= e($val('description')) ?>" maxlength="255"><?= field_error('description') ?></div>
            <div class="form-row form-row-3">
                <div class="form-group<?= has_error('color') ? ' has-error' : '' ?>"><label for="f-color">Farbe</label><select id="f-color" name="color"><?php foreach ($colors as $key => $label): ?><option value="<?= e($key) ?>"<?= selected($val('color', 'neutral'), $key) ?>><?= e($label) ?></option><?php endforeach; ?></select><?= field_error('color') ?></div>
                <div class="form-group<?= has_error('sort_order') ? ' has-error' : '' ?>"><label for="f-sort">Sortierung</label><input id="f-sort" type="number" name="sort_order" value="<?= e($val('sort_order', '0')) ?>" min="0" max="9999"><?= field_error('sort_order') ?></div>
                <?php if ($kind === 'priorities'): ?><div class="form-group<?= has_error('level') ? ' has-error' : '' ?>"><label for="f-level">Stufe</label><input id="f-level" type="number" name="level" value="<?= e($val('level', '2')) ?>" min="1" max="9"><?= field_error('level') ?></div><?php endif; ?>
                <?php if ($kind === 'types'): ?><div class="form-group<?= has_error('icon') ? ' has-error' : '' ?>"><label for="f-icon">Symbol</label><input id="f-icon" name="icon" value="<?= e($val('icon')) ?>" maxlength="40"><?= field_error('icon') ?></div><?php endif; ?>
            </div>
            <?php if ($kind === 'statuses'): ?><div class="form-row"><div class="form-group<?= has_error('category') ? ' has-error' : '' ?>"><label for="f-category">Kategorie</label><select id="f-category" name="category"><?php foreach ($statusCategories as $key => $label): ?><option value="<?= e($key) ?>"<?= selected($val('category', 'open'), $key) ?>><?= e($label) ?></option><?php endforeach; ?></select><?= field_error('category') ?></div><label class="checkbox-row"><input type="checkbox" name="pauses_sla" value="1"<?= form_checked($row, 'pauses_sla', false) ?>> SLA pausieren</label></div><?php endif; ?>
            <?php if ($kind === 'priorities'): ?><label class="checkbox-row"><input type="checkbox" name="is_default" value="1"<?= form_checked($row, 'is_default', false) ?>> Standardpriorität</label><?php endif; ?>
            <label class="checkbox-row"><input type="checkbox" name="is_active" value="1"<?= form_checked($row, 'is_active', true) ?>> Aktiv</label>
        <?php elseif ($kind === 'groups'): ?>
            <div class="form-row"><div class="form-group<?= has_error('name') ? ' has-error' : '' ?>"><label for="f-name">Name <span class="required">*</span></label><input id="f-name" name="name" value="<?= e($val('name')) ?>" maxlength="120" required autofocus><?= field_error('name') ?></div><div class="form-group<?= has_error('email') ? ' has-error' : '' ?>"><label for="f-email">E-Mail</label><input id="f-email" type="email" name="email" value="<?= e($val('email')) ?>" maxlength="255"><?= field_error('email') ?></div></div>
            <div class="form-group<?= has_error('description') ? ' has-error' : '' ?>"><label for="f-description">Beschreibung</label><input id="f-description" name="description" value="<?= e($val('description')) ?>" maxlength="255"><?= field_error('description') ?></div>
            <label class="checkbox-row mb-4"><input type="checkbox" name="is_active" value="1"<?= form_checked($row, 'is_active', true) ?>> Aktiv</label>
            <div class="grid grid-2"><div><h2>Mitglieder</h2><div class="member-list"><?php foreach ($agents as $a): ?><label><input type="checkbox" name="members[]" value="<?= (int) $a['id'] ?>"<?= $checkedIn($groupMembers, $a['id']) ?>> <?= e($a['display_name'] ?? $a['username']) ?></label><?php endforeach; ?></div></div><div><h2>Leads</h2><div class="member-list"><?php foreach ($agents as $a): ?><label><input type="checkbox" name="leads[]" value="<?= (int) $a['id'] ?>"<?= $checkedIn($groupLeads, $a['id']) ?>> <?= e($a['display_name'] ?? $a['username']) ?></label><?php endforeach; ?></div></div></div>
        <?php elseif ($kind === 'categories'): ?>
            <div class="form-row"><div class="form-group<?= has_error('name') ? ' has-error' : '' ?>"><label for="f-name">Name <span class="required">*</span></label><input id="f-name" name="name" value="<?= e($val('name')) ?>" maxlength="120" required autofocus><?= field_error('name') ?></div><div class="form-group<?= has_error('parent_id') ? ' has-error' : '' ?>"><label for="f-parent">Übergeordnet</label><select id="f-parent" name="parent_id"><?php $optionRows($roots, $val('parent_id'), '– Hauptkategorie –'); ?></select><?= field_error('parent_id') ?></div></div>
            <div class="form-row form-row-3"><div class="form-group"><label for="f-group">Standardgruppe</label><select id="f-group" name="default_group_id"><?php $optionRows($groups, $val('default_group_id')); ?></select></div><div class="form-group"><label for="f-priority">Standardpriorität</label><select id="f-priority" name="default_priority_id"><?php $optionRows($priorities, $val('default_priority_id')); ?></select></div><div class="form-group"><label for="f-sort">Sortierung</label><input id="f-sort" type="number" name="sort_order" value="<?= e($val('sort_order', '0')) ?>" min="0" max="9999"></div></div>
            <div class="form-group"><label for="f-description">Beschreibung</label><input id="f-description" name="description" value="<?= e($val('description')) ?>" maxlength="255"></div><label class="checkbox-row"><input type="checkbox" name="is_active" value="1"<?= form_checked($row, 'is_active', true) ?>> Aktiv</label>
        <?php elseif ($kind === 'slas'): ?>
            <div class="form-row"><div class="form-group<?= has_error('name') ? ' has-error' : '' ?>"><label for="f-name">Name <span class="required">*</span></label><input id="f-name" name="name" value="<?= e($val('name')) ?>" maxlength="120" required autofocus><?= field_error('name') ?></div><div class="form-group"><label for="f-priority">Priorität</label><select id="f-priority" name="priority_id"><?php $optionRows($priorities, $val('priority_id')); ?></select></div></div>
            <div class="form-row form-row-3"><div class="form-group"><label for="f-category">Kategorie</label><select id="f-category" name="category_id"><?php $optionRows($categories, $val('category_id')); ?></select></div><div class="form-group"><label for="f-response">Reaktionszeit (Min.)</label><input id="f-response" type="number" name="response_minutes" value="<?= e($val('response_minutes', '60')) ?>" min="1" required></div><div class="form-group"><label for="f-resolution">Lösungszeit (Min.)</label><input id="f-resolution" type="number" name="resolution_minutes" value="<?= e($val('resolution_minutes', '480')) ?>" min="1" required></div></div>
            <div class="form-group"><label for="f-description">Beschreibung</label><input id="f-description" name="description" value="<?= e($val('description')) ?>" maxlength="255"></div>
            <label class="checkbox-row"><input type="checkbox" name="business_hours_only" value="1"<?= form_checked($row, 'business_hours_only', false) ?> data-toggle-target="#business-hours"> Nur Geschäftszeiten zählen</label>
            <div id="business-hours" class="card mt-4"><div class="checkbox-row"><?php foreach ([1 => 'Mo', 2 => 'Di', 3 => 'Mi', 4 => 'Do', 5 => 'Fr', 6 => 'Sa', 7 => 'So'] as $day => $label): ?><label><input type="checkbox" name="business_days[]" value="<?= $day ?>"<?= $checkedIn($businessDays, $day) ?>> <?= e($label) ?></label><?php endforeach; ?></div><div class="form-row form-row-3"><div class="form-group"><label for="f-start">Beginn</label><input id="f-start" type="time" name="business_start" value="<?= e($val('business_start', '08:00')) ?>"></div><div class="form-group"><label for="f-end">Ende</label><input id="f-end" type="time" name="business_end" value="<?= e($val('business_end', '17:00')) ?>"></div><div class="form-group"><label for="f-escalation-group">Eskalationsgruppe</label><select id="f-escalation-group" name="escalation_group_id"><?php $optionRows($groups, $val('escalation_group_id')); ?></select></div></div></div>
            <div class="form-row form-row-3"><div class="form-group"><label for="f-warning">Warnschwelle (%)</label><input id="f-warning" type="number" name="warning_percent" value="<?= e($val('warning_percent', '75')) ?>" min="1" max="99"></div><div class="form-group"><label for="f-escalation">Eskalation (%)</label><input id="f-escalation" type="number" name="escalation_percent" value="<?= e($val('escalation_percent', '90')) ?>" min="1" max="100"></div><div class="form-group"><label for="f-sort">Sortierung</label><input id="f-sort" type="number" name="sort_order" value="<?= e($val('sort_order', '0')) ?>" min="0" max="9999"></div></div>
            <div class="checkbox-row"><label><input type="checkbox" name="is_default" value="1"<?= form_checked($row, 'is_default', false) ?>> Standard-SLA</label><label><input type="checkbox" name="is_active" value="1"<?= form_checked($row, 'is_active', true) ?>> Aktiv</label></div>
        <?php elseif ($kind === 'tags'): ?>
            <div class="form-row"><div class="form-group<?= has_error('name') ? ' has-error' : '' ?>"><label for="f-name">Name <span class="required">*</span></label><input id="f-name" name="name" value="<?= e($val('name')) ?>" maxlength="60" required autofocus><?= field_error('name') ?></div><div class="form-group<?= has_error('color') ? ' has-error' : '' ?>"><label for="f-color">Farbe</label><select id="f-color" name="color"><?php foreach ($colors as $key => $label): ?><option value="<?= e($key) ?>"<?= selected($val('color', 'neutral'), $key) ?>><?= e($label) ?></option><?php endforeach; ?></select><?= field_error('color') ?></div></div>
        <?php elseif ($kind === 'templates'): ?>
            <div class="form-row"><div class="form-group<?= has_error('name') ? ' has-error' : '' ?>"><label for="f-name">Name <span class="required">*</span></label><input id="f-name" name="name" value="<?= e($val('name')) ?>" maxlength="120" required autofocus><?= field_error('name') ?></div><div class="form-group"><label for="f-type">Tickettyp</label><select id="f-type" name="ticket_type_id"><?php $optionRows($types, $val('ticket_type_id')); ?></select></div></div>
            <div class="form-group"><label for="f-description">Beschreibung</label><input id="f-description" name="description" value="<?= e($val('description')) ?>" maxlength="255"></div>
            <div class="form-row form-row-3"><div class="form-group"><label for="f-category">Kategorie</label><select id="f-category" name="category_id" data-hd-category="#f-subcategory"><?php $optionRows($roots, $val('category_id')); ?></select></div><div class="form-group"><label for="f-subcategory">Unterkategorie</label><select id="f-subcategory" name="subcategory_id" data-selected="<?= e($val('subcategory_id')) ?>"><?php $optionRows($categories, $val('subcategory_id')); ?></select></div><div class="form-group"><label for="f-priority">Priorität</label><select id="f-priority" name="priority_id"><?php $optionRows($priorities, $val('priority_id')); ?></select></div></div>
            <div class="form-row form-row-3"><div class="form-group"><label for="f-group">Gruppe</label><select id="f-group" name="group_id"><?php $optionRows($groups, $val('group_id')); ?></select></div><div class="form-group"><label for="f-assignee">Bearbeiter</label><select id="f-assignee" name="assignee_user_id"><?php $optionRows($agents, $val('assignee_user_id'), '– nicht zugewiesen –'); ?></select></div><div class="form-group"><label for="f-sla">SLA</label><select id="f-sla" name="sla_id"><?php $optionRows($slas, $val('sla_id')); ?></select></div></div>
            <div class="form-group"><label for="f-subject">Betreff-Vorlage</label><input id="f-subject" name="subject" value="<?= e($val('subject')) ?>" maxlength="255"></div><div class="form-group"><label for="f-body">Beschreibungsvorlage</label><textarea id="f-body" name="body" rows="8"><?= e($val('body')) ?></textarea></div>
            <div class="form-row"><div class="form-group"><label for="f-tags">Tags</label><input id="f-tags" name="tags" value="<?= e($val('tags')) ?>" maxlength="500" data-hd-tags list="tag-suggestions"><datalist id="tag-suggestions"></datalist></div><div class="form-group"><label for="f-sort">Sortierung</label><input id="f-sort" type="number" name="sort_order" value="<?= e($val('sort_order', '0')) ?>" min="0" max="9999"></div></div>
            <div class="checkbox-row"><label><input type="checkbox" name="is_portal_visible" value="1"<?= form_checked($row, 'is_portal_visible', true) ?>> Im Portal sichtbar</label><label><input type="checkbox" name="is_active" value="1"<?= form_checked($row, 'is_active', true) ?>> Aktiv</label></div>
        <?php else: ?>
            <div class="form-row"><div class="form-group<?= has_error('name') ? ' has-error' : '' ?>"><label for="f-name">Name <span class="required">*</span></label><input id="f-name" name="name" value="<?= e($val('name')) ?>" maxlength="120" required autofocus><?= field_error('name') ?></div><div class="form-group<?= has_error('trigger_event') ? ' has-error' : '' ?>"><label for="f-trigger">Auslöser</label><select id="f-trigger" name="trigger_event"><?php foreach ($triggers as $trigger): ?><option value="<?= e($trigger) ?>"<?= selected($val('trigger_event', 'created'), $trigger) ?>><?= e($trigger) ?></option><?php endforeach; ?></select><?= field_error('trigger_event') ?></div></div>
            <div class="form-group"><label for="f-description">Beschreibung</label><input id="f-description" name="description" value="<?= e($val('description')) ?>" maxlength="255"></div>
            <div class="form-row"><div class="form-group<?= has_error('conditions') ? ' has-error' : '' ?>"><label for="f-conditions">Bedingungen (JSON)</label><textarea id="f-conditions" name="conditions" class="rule-json" rows="10"><?= e($val('conditions', '{"all":[{"field":"subject","op":"contains","value":"VPN"}],"any":[]}')) ?></textarea><?= field_error('conditions') ?></div><div class="form-group<?= has_error('actions') ? ' has-error' : '' ?>"><label for="f-actions">Aktionen (JSON)</label><textarea id="f-actions" name="actions" class="rule-json" rows="10"><?= e($val('actions', '{"set_group":"Network","set_priority":"high","add_tags":["vpn"],"notify_group":true,"notify_emails":["it@example.org"]}')) ?></textarea><?= field_error('actions') ?></div></div>
            <div class="rule-hints mb-4"><p>Felder: <?php foreach ($ruleFields as $hint): ?><code><?= e($hint) ?></code> <?php endforeach; ?></p><p>Operatoren: <?php foreach ($ruleOperators as $hint): ?><code><?= e($hint) ?></code> <?php endforeach; ?></p><p>Aktionen: <?php foreach ($ruleActions as $hint): ?><code><?= e($hint) ?></code> <?php endforeach; ?></p></div>
            <div class="form-row form-row-3"><div class="form-group"><label for="f-sort">Sortierung</label><input id="f-sort" type="number" name="sort_order" value="<?= e($val('sort_order', '0')) ?>" min="0" max="9999"></div><label class="checkbox-row"><input type="checkbox" name="stop_processing" value="1"<?= form_checked($row, 'stop_processing', false) ?>> Weitere Regeln stoppen</label><label class="checkbox-row"><input type="checkbox" name="is_active" value="1"<?= form_checked($row, 'is_active', true) ?>> Aktiv</label></div>
        <?php endif; ?>
        <div class="form-actions"><button type="submit" class="btn btn-primary"><?= icon('check') ?> <?= $isNew ? 'Anlegen' : 'Speichern' ?></button><a class="btn btn-ghost" href="<?= e($back) ?>">Abbrechen</a></div>
    </form>
</div>
<?php $innerContent = ob_get_clean(); include __DIR__ . '/../../partials/app_layout.php'; ?>
